package com.pepsa.pepsadispatch.orders.utils

object DeliveryOrdersConstants {
    const val STRING_INCOMING_ORDER_INTENT_ACTION =
        "com.pepsa.pepsadispatch.orders.INCOMING_ORDER_ACTION"
    const val TAG_INCOMING_ORDER_RECEIVED = "TAG_INCOMING_ORDER"
    const val INT_INCOMING_ORDER_PENDING_INTENT_REQUEST_CODE = 111
    const val INCOMING_ORDER_NOTIFICATION_CHANNEL_ID = "INCOMING_ORDER_NOTIFICATION_CHANNEL_ID"
    const val INT_INCOMING_NOTIFICATION_ID = 0
    const val STRING_GET_ROUTE_ORDER_WORKER_INPUT_DATA_TAG =
        "STRING_GET_ROUTE_ORDER_WORKER_INPUT_DATA_TAG"
    const val STRING_GET_ROUTE_ORDER_WORKER_OUTPUT_DATA_TAG =
        "STRING_GET_ROUTE_ORDER_WORKER_OUTPUT_DATA_TAG"
    const val TAG_INCOMING_ORDER_DIALOG = "TAG_INCOMING_ORDER_DIALOG"
    const val TAG_INCOMING_ORDER_LOGGER = "TAG_INCOMING_ORDER_LOGGER====>"
    const val TAG_NEW_TOKEN_LOGGER = "TAG_NEW_TOKEN_LOGGER====>"
    const val TAG_RING_TONE_ERROR_LOGGER = "TAG_RING_TONE_ERROR_LOGGER===>"
}
